name: ocm-action
# trigger manually
run-name: Build component using ocm github action
on:
  workflow_dispatch:
jobs:
  build-with-ocm-action:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Install OCM
      uses: open-component-model/ocm-setup-action@main
    - name: Create component
      uses: open-component-model/ocm-action@main
      with:
        action: create_component
        component: github.com/jenhs007/simpleserver
        version: 1.0.0
        provider: github.com/jensh007
    - name: Add Resources
      uses: open-component-model/ocm-action@main
      with:
        action: add_resources
        resources: resources.yaml
    - name: Push
      uses: open-component-model/ocm-action@main
      with:
        action: push_ctf
        comprepo_url: ghcr.io/jensh007
        comprepo_user: ${{ env.GITHUB_ACTOR }}
        comprepo_password: ${{ secrets.GITHUB_TOKEN }}



