# SPDX-FileCopyrightText: 2022 2022-2023 SAP SE or an SAP affiliate company and Open Component Model contributors.
#
# SPDX-License-Identifier: Apache-2.0

name: build-and-ocm
# trigger manually
run-name: Build image and create component version without makefile
on:
  workflow_dispatch:
env:
  VERSION: "1.0.0"
  COMP_NAME: acme.org/demo/simpleserver
  PROVIDER: github.com/jensh007
  REPO_URL: ghcr.io/jensh007/ocm
jobs:
  build-and-create-ocm:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: setup OCM
        uses: open-component-model/ocm-setup-action@main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders
      - name: Set up Docker Buildx
        timeout-minutes: 5
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
      - name: Build amd64
        id: build_amd64
        uses: docker/build-push-action@v3
        with:
          push: false
          load: true
          platforms: linux/amd64
          tags: ghcr.io/acme/simpleserver:${{ env.VERSION }}-linux-amd64
      - name: Build arm64
        id: build_arm64
        uses: docker/build-push-action@v3
        with:
          push: false
          load: true
          platforms: linux/arm64
          tags: ghcr.io/acme/simpleserver:${{ env.VERSION }}-linux-arm64
      - name: create OCM component version
        uses: open-component-model/ocm-action@main
        with:
          action: create_component
          component: ${{ env.COMP_NAME }}
          provider: ${{ env.PROVIDER }}
          version: ${{ env.VERSION }}
      # - name: write OCM settings file
      #   run: |
      #     cat > gen/ocm/settings.yaml<< EOF
      #     MULTI: true
      #     IMAGE: ghcr.io/acme/simpleserver:${{ env.VERSION }}
      #     PLATFORMS: "linux/amd64 linux/arm64"
      #     EOF
      - name: add OCM resources
        uses: open-component-model/ocm-action@main
        with:
          action: add_resources
          component: ${{ env.COMP_NAME }}
          resources: resources.yaml
          templater: spiff
          version: ${{ env.VERSION }}
          var_values: |
            MULTI: true
            IMAGE: ghcr.io/acme/simpleserver:${{ env.VERSION }}
            PLATFORMS: "linux/amd64 linux/arm64"
      - name: create OCM transport archive
        uses: open-component-model/ocm-action@main
        with:
          action: add_component
          ctf: gen/ctf
      - name: push OCM transport archive
        uses: open-component-model/ocm-action@main
        with:
          action: push_ctf
          comprepo_user: ${{ env.GITHUB_ACTOR }}
          comprepo_password: ${{ secrets.GITHUB_TOKEN }}
          ctf: gen/ctf
          comprepo_url: ${{ env.REPO_URL }}
      - name: Upload transport archive
        uses: actions/upload-artifact@v3
        with:
          name: ocm-simpleserver-ctf.zip
          path: |
            gen/ctf
