name: build-and-ocm
# trigger manually
run-name: Dummy Github Action
on:
  workflow_dispatch:
jobs:
  build-multiarch:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3