name: build
# trigger manually
run-name: Build Simple Server multiarch images
on:
  workflow_dispatch:
jobs:
  build-multiarch:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
