name: build-and-ocm
# trigger manually
run-name: Build image and create component version without makefile
on:
  workflow_dispatch:
jobs:
  build-and-create-ocm:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: setup OCM
        uses: open-component-model/ocm-setup-action@main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders
      - name: Set up Docker Buildx
        timeout-minutes: 5
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
      - name: Build amd64
        id: build_amd64
        uses: docker/build-push-action@v3
        with:
          push: false
          load: true
          platforms: linux/amd64
          tags: ghcr.io/acme/simpleserver:0.1.0-linux-amd64
      - name: Build arm64
        id: build_arm64
        uses: docker/build-push-action@v3
        with:
          push: false
          load: true
          platforms: linux/arm64
          tags: ghcr.io/acme/simpleserver:0.1.0-linux-arm64
      - name: Create OCM
        uses: open-component-model/ocm-action@test
        with:
          action: create_component
          component: acme.org/demo/simpleserver
          version: 1.0.0
      - name: add OCM resources
        uses: open-component-model/ocm-action@test
        with:
          action: add_resources
          component: acme.org/demo/simpleserver
          resources: resources.yaml
          templater: spiff
          version: 1.0.0
      - name: create OCM transport archive
        uses: open-component-model/ocm-action@test
        with:
          action: add_component
          ctf: gen/ctf
      - name: Upload transport archive
        uses: actions/upload-artifact@v3
        with:
          name: ocm-simpleserver
          path: |
            gen/ctf
