name: build
# trigger manually
run-name: Build Simple Server multiarch images
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'
        type: choice
        options:
        - info
        - warning
        - debug
jobs:
  build-multiarch:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    # doc: https://github.com/marketplace/actions/build-and-push-docker-images
    - name: Build amd64
      id: build_amd64
      uses: docker/build-push-action@v3
      with:
        push: false
        load: true
        platforms: linux/amd64
        tags: ghcr.io/acme/simpleserver:0.1.0-linux-amd64
    - name: Build arm64
      id: build_arm64
      uses: docker/build-push-action@v3
      with:
        push: false
        load: true
        platforms: linux/arm64
        tags: ghcr.io/acme/simpleserver:0.1.0-linux-arm64
    - name: Report Image digest amd64
      run: |
        echo ${{ steps.build_amd64.outputs.digest }}
        echo ${{ steps.build_amd64.outputs.imageid }}
        echo ${{ steps.build_amd64.outputs.metadata }}
    - name: Report Image digest arm64
      run: |
        echo ${{ steps.build_arm64.outputs.digest }}
        echo ${{ steps.build_arm64.outputs.imageid }}
        echo ${{ steps.build_arm64.outputs.metadata }}
