name: make
# trigger manually
run-name: Build image and CTF with makefile
on:
  workflow_dispatch:
jobs:
  build-multiarch:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    # - name: build single arch docker image
    #   run: make image
    - name: build component archive
      run: make MULTI=false  ca
    - name: build CTF archive
      run: make MULTI=false ctf
  use-ocm:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: build component archive
        uses: open-component-model/ocm-setup-action@main
        run: make MULTI=false ctf
