name: make
# trigger manually
run-name: Build single architecture image with makefile
on:
  workflow_dispatch:
jobs:
  build-multiarch:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: build single arch docker image
      run: make image