name: make
# trigger manually
run-name: Build image and CTF with makefile
on:
  workflow_dispatch:
jobs:
  # build-with-docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Check out the repo
  #     uses: actions/checkout@v3
  #   - name: Set up QEMU
  #     uses: docker/setup-qemu-action@v2
  #   - name: Set up Docker Context for Buildx
  #     id: buildx-context
  #     run: |
  #       docker context create builders
  #   - name: Set up Docker Buildx
  #     timeout-minutes: 5
  #     uses: docker/setup-buildx-action@v2
  #     with:
  #       version: latest
  #       endpoint: builders # self-hosted
  #   - name: build multi arch docker image
  #     run: make multi
  use-ocm:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: setup OCM
        uses: open-component-model/ocm-setup-action@main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders
      - name: Set up Docker Buildx
        timeout-minutes: 5
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
      - name: build single transport archive
        run: make MULTI=false ctf
      - name: Archive transport archive
        uses: actions/upload-artifact@v3
        with:
          name: ocm-simpleserver
          path: |
            gen/ctf
  push:
    needs: use-ocm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: setup OCM
        uses: open-component-model/ocm-setup-action@main
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: test docker config
        run: cat ~/.docker/config.json
      - name: write OCM config file
        run: |
          cat > ~/.ocmconfig<< EOF
          type: generic.config.ocm.software/v1
          configurations:
            - type: credentials.config.ocm.software
              repositories:
                - repository:
                    type: DockerConfig/v1
                    dockerConfigFile: "~/.docker/config.json"
                    propagateConsumerIdentity: true
          EOF
      - name: Download CTF from build steps
        uses: actions/download-artifact@v3
        with:
          name: ocm-simpleserver
          path: gen/ctf
      - name: push CTF to OCI registry
        run: make GITHUBORG=jensh007 push
      - name: describe component version
        run: make describe
      - name: get component descriptor
        run: make descriptor

