name: make
# trigger manually
run-name: Build image and CTF with makefile
on:
  workflow_dispatch:
jobs:
  # build-with-docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Check out the repo
  #     uses: actions/checkout@v3
  #   - name: Set up QEMU
  #     uses: docker/setup-qemu-action@v2
  #   - name: Set up Docker Context for Buildx
  #     id: buildx-context
  #     run: |
  #       docker context create builders
  #   - name: Set up Docker Buildx
  #     timeout-minutes: 5
  #     uses: docker/setup-buildx-action@v2
  #     with:
  #       version: latest
  #       endpoint: builders # self-hosted
  #   - name: build multi arch docker image
  #     run: make multi
  use-ocm:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: setup OCM
        uses: open-component-model/ocm-setup-action@main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders
      - name: Set up Docker Buildx
        timeout-minutes: 5
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
      - name: build single transport archive
        run: make MULTI=false ctf
  push:
    needs: use-ocm
    runs-on: ubuntu-latest
    steps:
      - name: setup OCM
        uses: open-component-model/ocm-setup-action@main
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: push CTF to OCI registry
        run: make GITHUBORG=jensh007 push
      - name: describe component version
        run: make describe
      - name: get component descriptor
        run: make descriptor
