name: make
# trigger manually
run-name: Build image and CTF with makefile
on:
  workflow_dispatch:
jobs:
  build-singlearch:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: build single arch docker image
      run: make multi
  use-ocm:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: setup OCM
        uses: open-component-model/ocm-setup-action@main
      - name: build component archive
        run: make MULTI=false ctf
